export const CREATE_EVENT = "CREATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const DELETE_CHECKED_EVENTS = "DELETE_CHECKED_EVENTS";
export const CHECK_EVENT = "CHECK_EVENT";
export const CHECK_ALL_EVENTS = "CHECK_ALL_EVENTS";

export const ADD_OPERATION_LOG = "ADD_OPERATION_LOG";
export const DELETE_ALL_OPERATION_LOGS = "DELETE_ALL_OPERATION_LOGS";
